export interface MenuItem {
  id: string;
  name: string;
  description: string;
  weight: string;
  price: number;
  category: string;
  image: string;
  badge?: 'hit' | 'new' | 'special';
}

export interface Category {
  id: string;
  name: string;
  emoji: string;
  image: string;
}

export const categories: Category[] = [
  { id: 'pizza', name: 'Піца', emoji: '🍕', image: '/pizza.png' },
  { id: 'sushi', name: 'Суші & Роли', emoji: '🍣', image: '/sushi.png' },
  { id: 'burgers', name: 'Бургери', emoji: '🍔', image: '/burger.png' },
  { id: 'hotdogs', name: 'Хот-Доги', emoji: '🌭', image: '/snacks.png' },
  { id: 'soup', name: 'Перші страви', emoji: '🍲', image: '/soup.png' },
  { id: 'hot', name: 'Гарячі закуски', emoji: '🔥', image: '/snacks.png' },
  { id: 'crispy', name: 'Хрустке і швидке', emoji: '⚡', image: '/snacks.png' },
  { id: 'salads', name: 'Салати', emoji: '🥗', image: '/salad.png' },
  { id: 'drinks', name: 'Напої', emoji: '🥤', image: '/dessert.png' },
  { id: 'desserts', name: 'Десерти', emoji: '🍰', image: '/dessert.png' },
];

export const menuItems: MenuItem[] = [
  // ПІЦА
  {
    id: 'pizza-1',
    name: 'Шотландська',
    description: 'Томлена свинина з маринованим огірком, цибулею, соусом фірмовим, сир',
    weight: '450 г',
    price: 280,
    category: 'pizza',
    image: '/pizza_shotlandska.png',
    badge: 'hit',
  },
  {
    id: 'pizza-2',
    name: 'Морська',
    description: 'Лосось, мідії, соус альфредо, сир моцарелла, помідор черрі',
    weight: '450 г',
    price: 320,
    category: 'pizza',
    image: '/pizza_morska.png',
    badge: 'hit',
  },
  {
    id: 'pizza-3',
    name: 'Філадельфія лосось',
    description: 'Лосось, крем-сир, огірок, каперси, цибуля червона, соус',
    weight: '450 г',
    price: 320,
    category: 'pizza',
    image: '/pizza_philadelphia.png',
  },
  {
    id: 'pizza-4',
    name: 'Дует',
    description: 'Креветки, американський бекон, моцарелла, соус фірмовий, помідор',
    weight: '450 г',
    price: 320,
    category: 'pizza',
    image: '/pizza_duet.png',
  },
  {
    id: 'pizza-5',
    name: 'Пеппероні',
    description: 'Ковбаска пеппероні, соус томатний, сир моцарелла, спеції',
    weight: '450 г',
    price: 280,
    category: 'pizza',
    image: '/pizza_pepperoni.png',
  },
  {
    id: 'pizza-6',
    name: 'Чотири сири',
    description: 'Моцарелла, пармезан, чеддер, горгонзола, соус вершковий',
    weight: '450 г',
    price: 300,
    category: 'pizza',
    image: '/pizza_four_cheese.png',
  },
  {
    id: 'pizza-7',
    name: 'Барбекю',
    description: 'Курка гриль, бекон, болгарський перець, соус BBQ, моцарелла',
    weight: '450 г',
    price: 290,
    category: 'pizza',
    image: '/pizza_bbq.png',
  },
  {
    id: 'pizza-8',
    name: 'Маргарита',
    description: 'Томатний соус, сир моцарелла, свіжий базилік, оливкова олія',
    weight: '400 г',
    price: 250,
    category: 'pizza',
    image: '/pizza_margarita.png',
  },

  // СУШІ
  {
    id: 'sushi-set1',
    name: 'Сет № 1',
    description: 'Великий асорті сет: Філадельфія рол, Каліфорнія рол, Маки лосось, Нігірі (48 шт)',
    weight: '1200 г',
    price: 1400,
    category: 'sushi',
    image: '/sushi_set1.png',
    badge: 'hit',
  },
  {
    id: 'sushi-set2',
    name: 'Сет № 2',
    description: 'Преміум асорті: Роял рол, Гарячий рол, Запечений рол, Якудза рол (56 шт)',
    weight: '1400 г',
    price: 1500,
    category: 'sushi',
    image: '/sushi_set2.png',
    badge: 'hit',
  },
  {
    id: 'sushi-tempura-spinach',
    name: 'Темпура рол з шпинатом',
    description: 'Креветка темпура, шпинат, крем-сир, огірок, тобіко, кунжут, соус унагі',
    weight: '450 г',
    price: 400,
    category: 'sushi',
    image: '/sushi_tempura_spinach.png',
  },
  {
    id: 'sushi-tempura-caesar',
    name: 'Темпура рол Цезарь',
    description: 'Курка, помідор, салат, крем-сир, пармезан, соус цезар',
    weight: '450 г',
    price: 400,
    category: 'sushi',
    image: '/sushi_tempura_caesar.png',
  },
  {
    id: 'sushi-dragon',
    name: 'Золотий Дракон',
    description: 'Вугор, огірок, тобіка, норі, кунжут, рис, крем-сир, васабі, імбир, соус унагі',
    weight: '450 г',
    price: 420,
    category: 'sushi',
    image: '/sushi_dragon.png',
    badge: 'special',
  },
  {
    id: 'sushi-yakuza',
    name: 'Якудза рол',
    description: 'Лосось, креветка, норі, рис, ікра тобіко, крем-сир, огірок, унагі соус, кунжут',
    weight: '500 г',
    price: 450,
    category: 'sushi',
    image: '/sushi_yakuza.png',
    badge: 'new',
  },
  {
    id: 'sushi-hiyashi',
    name: 'Хіяши рол',
    description: 'Лосось/креветка/тунець/вугор, огірок, тобіка, норі, рис, крем-сир',
    weight: '450 г',
    price: 350,
    category: 'sushi',
    image: '/sushi_hiyashi.png',
  },
  {
    id: 'sushi-philadelphia',
    name: 'Філадельфія рол',
    description: 'Лосось/креветка/тунець/асорті, огірок, норі, рис, крем-сир, соус унагі',
    weight: '450 г',
    price: 350,
    category: 'sushi',
    image: '/sushi_philadelphia.png',
    badge: 'hit',
  },
  {
    id: 'sushi-california',
    name: 'Каліфорнія рол',
    description: 'Лосось/креветка/тунець/вугор, норі, рис, ікра тобіко, крем-сир, огірок',
    weight: '450 г',
    price: 350,
    category: 'sushi',
    image: '/sushi_california.png',
  },
  {
    id: 'sushi-royal',
    name: 'Роял рол з печеним лососем',
    description: 'Лосось, вугор, норі, рис, крем-сир, хіяши вакаме, огірок, тобіко',
    weight: '450 г',
    price: 400,
    category: 'sushi',
    image: '/sushi_royal.png',
  },
  {
    id: 'sushi-kyiv',
    name: 'Київ рол лосось з пармезаном',
    description: 'Норі, рис, крем-сир, пармезан, ікра тобіко, огірок, лосось',
    weight: '450 г',
    price: 400,
    category: 'sushi',
    image: '/sushi_kyiv.png',
    badge: 'new',
  },
  {
    id: 'sushi-tomyam-roll',
    name: 'ТОМ Ям рол',
    description: 'Лосось, креветка, мідії, огірок, тобіка, норі, рис, крем-сир, сир чеддер',
    weight: '450 г',
    price: 400,
    category: 'sushi',
    image: '/sushi_tomyam_roll.png',
  },
  {
    id: 'sushi-baked',
    name: 'Запечений рол',
    description: 'Лосось/тунець/креветка, крем-сир, огірок, сир моцарелла, ікра тобіка',
    weight: '450 г',
    price: 400,
    category: 'sushi',
    image: '/sushi_baked.png',
    badge: 'hit',
  },
  {
    id: 'sushi-hot',
    name: 'Гарячий рол',
    description: 'Лосось, крем-сир, огірок, ікра тобіка, кунжут, соус унагі, норі, рис',
    weight: '500 г',
    price: 400,
    category: 'sushi',
    image: '/sushi_hot.png',
  },
  {
    id: 'sushi-shawarma',
    name: 'Суші шаурма',
    description: 'Лосось/тунець/креветка/вугор, крем-сир, огірок, салат айсберг, ікра тобіка',
    weight: '350 г',
    price: 250,
    category: 'sushi',
    image: '/sushi_shawarma.png',
  },
  {
    id: 'sushi-burger',
    name: 'Суші Бургер',
    description: 'Лосось/тунець/креветка/вугор, крем-сир, ікра тобіка, салат айсберг, огірок',
    weight: '350 г',
    price: 300,
    category: 'sushi',
    image: '/sushi_burger.png',
  },
  {
    id: 'sushi-maki',
    name: 'Макі лосось/тунець/креветка',
    description: 'Норі, рис, васабі, імбир, соєвий соус',
    weight: '250 г',
    price: 170,
    category: 'sushi',
    image: '/sushi_maki.png',
  },
  {
    id: 'sushi-nigiri',
    name: 'Нігірі лосось/тунець/креветка',
    description: 'Норі, рис, васабі, імбир, соєвий соус',
    weight: '200 г',
    price: 170,
    category: 'sushi',
    image: '/sushi_nigiri.png',
  },

  // БУРГЕРИ
  {
    id: 'burger-giant',
    name: 'Бургер Велетень',
    description: 'Яловича котлета, салат айсберг, американський бекон, цибулеві кільця, помідор, сир чеддер, соус фірмовий, солоний огірок, булочка',
    weight: '500 г',
    price: 250,
    category: 'burgers',
    image: '/burger.png',
    badge: 'hit',
  },
  {
    id: 'burger-hamburger',
    name: 'Гамбургер',
    description: 'Котлета яловичина, огірок маринований, помідор, сир чеддер, соус фірмовий, булочка',
    weight: '300 г',
    price: 180,
    category: 'burgers',
    image: '/burger.png',
  },
  {
    id: 'burger-cheeseburger',
    name: 'Чізбургер',
    description: 'Курка, сир, соус фірмовий, булочка',
    weight: '200 г',
    price: 70,
    category: 'burgers',
    image: '/burger.png',
  },

  // ХОТ-ДОГИ
  {
    id: 'hd-hotdog',
    name: 'Хот-Дог',
    description: 'Сосиска, соус, булочка',
    weight: '150 г',
    price: 60,
    category: 'hotdogs',
    image: '/snacks.png',
  },
  {
    id: 'hd-corndog',
    name: 'Корн-Дог',
    description: 'Сосиска в темпурі',
    weight: '150 г',
    price: 70,
    category: 'hotdogs',
    image: '/snacks.png',
  },
  {
    id: 'hd-panini',
    name: 'Паніні папероні',
    description: 'Ковбаска, булочка, фірмовий соус',
    weight: '200 г',
    price: 70,
    category: 'hotdogs',
    image: '/snacks.png',
  },
  {
    id: 'hd-mini-pizza',
    name: 'Міні піца папероні',
    description: 'Ковбаска, соус, сир',
    weight: '250 г',
    price: 80,
    category: 'hotdogs',
    image: '/pizza.png',
  },

  // ПЕРШІ СТРАВИ
  {
    id: 'soup-mushroom',
    name: 'Крем-суп грибний',
    description: 'Печериці, цибуля, вершки',
    weight: '350 г',
    price: 180,
    category: 'soup',
    image: '/soup.png',
  },
  {
    id: 'soup-chicken',
    name: 'Курячий бульйон',
    description: 'Бульйон, курка, локшина, яйце',
    weight: '350 г',
    price: 150,
    category: 'soup',
    image: '/soup.png',
  },
  {
    id: 'soup-tomyam',
    name: 'ТОМ Ям',
    description: 'Лосось, мідії, креветки, печериці, помідор, рис, паста том-ям',
    weight: '400 г',
    price: 250,
    category: 'soup',
    image: '/soup.png',
    badge: 'hit',
  },

  // ГАРЯЧІ ЗАКУСКИ
  {
    id: 'hot-deruny-scottish',
    name: 'Деруни по-шотландськи',
    description: 'Картопля, огірок маринований, свинина, крем-сир, цибулевий кранч, соус кислосолодкий',
    weight: '300 г',
    price: 200,
    category: 'hot',
    image: '/snacks.png',
    badge: 'special',
  },
  {
    id: 'hot-deruny-mushroom',
    name: 'Деруни з грибами',
    description: 'Картопля, гриби, вершковий соус',
    weight: '300 г',
    price: 150,
    category: 'hot',
    image: '/snacks.png',
  },
  {
    id: 'hot-deruny-sour-cream',
    name: 'Деруни зі сметаною',
    description: 'Картопляні деруни зі сметаною',
    weight: '180 г',
    price: 100,
    category: 'hot',
    image: '/snacks.png',
  },
  {
    id: 'hot-chicken-spinach',
    name: 'Куряче філе з шпинатом та соусом чеддер',
    description: 'Курка, вершки, бекон, сир чеддер',
    weight: '270 г',
    price: 250,
    category: 'hot',
    image: '/snacks.png',
    badge: 'hit',
  },
  {
    id: 'hot-ribs-bbq',
    name: 'Ребра BBQ',
    description: 'Свинячі ребра у соусі барбекю',
    weight: '300 г',
    price: 200,
    category: 'hot',
    image: '/snacks.png',
  },
  {
    id: 'hot-meat-pan',
    name: "М'ясна Пательня з овочами",
    description: 'Свинина, спаржева фасоля, помідор, картопля, гриби, цибуля, соус',
    weight: '450 г',
    price: 300,
    category: 'hot',
    image: '/snacks.png',
  },
  {
    id: 'hot-wings-yakitori',
    name: 'Крильця Якіторі',
    description: 'Курячі крильця, соус теріякі, спеції, кунжут',
    weight: '300 г',
    price: 180,
    category: 'hot',
    image: '/snacks.png',
    badge: 'hit',
  },
  {
    id: 'hot-salmon-steak',
    name: 'Стейк Лосося/Тунця',
    description: 'Стейк риби з картоплею фрі та соусом',
    weight: '350 г',
    price: 300,
    category: 'hot',
    image: '/snacks.png',
  },

  // ХРУСТКЕ І ШВИДКЕ
  {
    id: 'crispy-nuggets',
    name: 'Курячі нагетси',
    description: 'Куряче філе, спеції, панко',
    weight: '100 г',
    price: 80,
    category: 'crispy',
    image: '/snacks.png',
  },
  {
    id: 'crispy-mussels',
    name: 'Мідії теріякі',
    description: 'Мідії, хіяши вакаме, соус теріякі, соус кислосолодкий, кунжут',
    weight: '200 г',
    price: 170,
    category: 'crispy',
    image: '/snacks.png',
  },
  {
    id: 'crispy-fries',
    name: 'Картопля по-селянськи / Фрі',
    description: 'Хрустка картопля по-селянськи або картопля фрі',
    weight: '150 г',
    price: 80,
    category: 'crispy',
    image: '/snacks.png',
  },
  {
    id: 'crispy-mozzarella',
    name: 'Моцарелла фрі',
    description: 'Сир моцарелла, спеції, панко',
    weight: '100 г',
    price: 100,
    category: 'crispy',
    image: '/snacks.png',
  },
  {
    id: 'crispy-onion-rings',
    name: 'Цибулеві кільця',
    description: 'Цибуля, спеції, кляр',
    weight: '120 г',
    price: 80,
    category: 'crispy',
    image: '/snacks.png',
  },
  {
    id: 'crispy-calamari',
    name: 'Кільця кальмарів',
    description: 'Кальмар, спеції, кляр',
    weight: '120 г',
    price: 80,
    category: 'crispy',
    image: '/snacks.png',
  },
  {
    id: 'crispy-shrimp',
    name: 'Креветка смажена',
    description: 'Креветка, спеції',
    weight: '150 г',
    price: 220,
    category: 'crispy',
    image: '/snacks.png',
  },
  {
    id: 'crispy-croutons',
    name: 'Сухарики з пармезаном',
    description: 'Хліб, спеції, сир пармезан',
    weight: '200 г',
    price: 80,
    category: 'crispy',
    image: '/snacks.png',
  },
  {
    id: 'crispy-sauce',
    name: 'Соус в асортименті',
    description: 'Часниковий, Фірмовий, Кетчуп, Майонез, Томатний, Діабло, Цезар, Унагі, Солодкий чилі, Сирний, BBQ',
    weight: '50 г',
    price: 50,
    category: 'crispy',
    image: '/snacks.png',
  },

  // САЛАТИ
  {
    id: 'salad-caesar',
    name: 'Салат Юлій Цезар курка',
    description: 'Бекон та курка, салат айсберг, соус "Цезар", крутони, помідор, яйце, пармезан',
    weight: '300 г',
    price: 280,
    category: 'salads',
    image: '/salad.png',
    badge: 'hit',
  },
  {
    id: 'salad-salmon',
    name: 'Салат з лососем гравлакс',
    description: 'Салат мікс, лосось, чука, крем-сир, помідор, соус кунжутний, кунжут, пармезан',
    weight: '300 г',
    price: 300,
    category: 'salads',
    image: '/salad.png',
  },
  {
    id: 'salad-shrimp',
    name: 'Салат з креветкою',
    description: 'Салат мікс, креветка, шампіньйон, помідор, крем-сир, соус унагі, кунжут, пармезан',
    weight: '300 г',
    price: 300,
    category: 'salads',
    image: '/salad.png',
  },
  {
    id: 'salad-gourmet',
    name: 'Гурман',
    description: 'Салат мікс, вугор, крем-сир, соус кисло-солодкий, помідор, огірок, кунжут, пармезан',
    weight: '300 г',
    price: 300,
    category: 'salads',
    image: '/salad.png',
    badge: 'special',
  },

  // НАПОЇ
  {
    id: 'drink-wine-500',
    name: 'Вино в асортименті Одеса (500 мл)',
    description: 'Вино в асортименті від одеських виробників',
    weight: '500 мл',
    price: 50,
    category: 'drinks',
    image: '/dessert.png',
  },
  {
    id: 'drink-wine-1000',
    name: 'Вино в асортименті Одеса (1000 мл)',
    description: 'Вино в асортименті від одеських виробників',
    weight: '1000 мл',
    price: 70,
    category: 'drinks',
    image: '/dessert.png',
  },
  {
    id: 'drink-water',
    name: 'Вода',
    description: 'Газована чи не газована',
    weight: '500 мл',
    price: 30,
    category: 'drinks',
    image: '/dessert.png',
  },
  {
    id: 'drink-soda',
    name: 'Кола / Фанта / Спрайт / Fuze Tea',
    description: 'Газовані напої в асортименті',
    weight: '500 мл',
    price: 40,
    category: 'drinks',
    image: '/dessert.png',
  },
  {
    id: 'drink-juice',
    name: 'Сік в асортименті',
    description: 'Свіжий сік у різних смаках',
    weight: '250 мл',
    price: 30,
    category: 'drinks',
    image: '/dessert.png',
  },

  // ДЕСЕРТИ
  {
    id: 'dessert-macarons',
    name: 'Макаруни в асортименті',
    description: 'Французькі макаруни у різних смаках',
    weight: '1 шт',
    price: 70,
    category: 'desserts',
    image: '/dessert.png',
    badge: 'new',
  },
  {
    id: 'dessert-bomb',
    name: 'Тістечко мега бомба',
    description: 'Шоколадне тістечко з сюрпризом всередині',
    weight: '1 шт',
    price: 50,
    category: 'desserts',
    image: '/dessert.png',
  },
];
